theme: jekyll-theme-hacker
url: "https://www.mousehelper.cls-system.es"
image: //assets/images/MouseHelper.png
logo: //assets/images/MouseHelper.png
title: "MouseHelper"
email: "mousehelper@outlook.es"
lang: es_ES
description: "Software gratuito de ClsSystem para mejorar el manejo del mouse en Windows, para personas con discapacidad motora como la enfermedad de Parkinson"
twittter:
    username: mouse_helper
facebook:
    app_id: 338370567315666
social:
  name: MouseHelper
  links:
    - https://twitter.com/mouse_helper
    - https://www.facebook.com/ClsSystemMouseHelper

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-175471186-1

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
